### ISSUE TITLE
Errors initialising wallet with Next.JS

### ISSUE THREAD

**Issue by paragmightybear** [0xsequence/sequence.js#358]
Trying to initialise wallet in Next JS app with the following code:
`const wallet = await sequence.initWallet('goerli');
	const connectDetails = await wallet.connect({
		networkId: 5,
		app: "Demo App",
	});`
	
Doing this gives the following error:

`
error - unhandledRejection: ReferenceError: window is not defined
    at WindowMessageProvider.register (...node_modules/@0xsequence/provider/dist/0xsequence-provider.cjs.dev.js:2526:7)
    at MuxMessageProvider.register (...node_modules/@0xsequence/provider/dist/0xsequence-provider.cjs.dev.js:2381:23)
    at Wallet.init (...node_modules/@0xsequence/provider/dist/0xsequence-provider.cjs.dev.js:3321:38)
    at new Wallet (...node_modules/@0xsequence/provider/dist/0xsequence-provider.cjs.dev.js:3612:10)
    at Object.initWallet (...node_modules/@0xsequence/provider/dist/0xsequence-provider.cjs.dev.js:3813:20)
    at initSequenceWallet (webpack-internal:///./pages/_app.tsx:84:77)
    at eval (webpack-internal:///./pages/_app.tsx:91:1)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
`
Currently using the following packages in this project (only listing relevant packages):
`
"dependencies": {
		"0xsequence": "^0.43.20",
		"@0xsequence/rainbowkit-plugin": "^1.0.4",
		"@0xsequence/wagmi-connector": "^1.0.3",
		"@rainbow-me/rainbowkit": "^0.7.4",
		"@rainbow-me/rainbowkit-siwe-next-auth": "^0.1.5",
		"ethers": "^5.0.0",
		"next": "^12.3.3",
		"next-auth": "^4.17.0",
		"next-axiom": "^0.15.1",
		"next-seo": "^5.15.0",
		"react": "^18.1.0",
		"react-dom": "^18.2.0",
		"siwe": "^2.1.3",
		"swr": "2.0.0",
		"wagmi": "0.6.8"
	},`

Is there a recommended way to work with Next.JS?

**Comment by pkieltyka** [comment]
this is now resolved in the latest versions of rainbowkit-plugin
